### ISSUE TITLE
Anyone can transfrom the Stereo Madness music into a mp3 file?

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#133]
The NES one ofc, not the real one.
Why I need it? I'm cooking smth (🥘🔥)

**Comment by zephyrside** [comment]
best i can offer is a .wav
https://drive.google.com/file/d/1hwqv-GAAOoKzzK1YhcypUDb2rVbCd6aY/view?usp=sharing

**Comment by nicco1690** [comment]
Can't do it because I'm on mobile atm, but here's how you can:
- Download Famidash's source code ('Download as ZIP' from [here](https://github.com/famidash/famidash))
- Download [Dn-Famitracker](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/releases/tag/Dn0.5.0.2)
- Open famidash/MUSIC/MODULES/music_master.dnm in Dn-Famitracker
- Go to File -> Export WAV, save it somewhere
- Download Audacity
- Open the newly exported file in audacity
- Go to File -> Export as... -> in the dropdown, change WAV to MP3

**Comment by LNLenost** [comment]
> best i can offer is a .wav https://drive.google.com/file/d/1hwqv-GAAOoKzzK1YhcypUDb2rVbCd6aY/view?usp=sharing

wav is ok, thx :D

give me 20 mins and you'll see what I cooked

**Comment by PinguLinux** [comment]
why dont you join the discord server for famidash? i think it would be better to ask there instead of here

**Comment by LNLenost** [comment]
> why dont you join the discord server for famidash? i think it would be better to ask there instead of here

My parents wont let me install discord. I can join some servers on my dad's one but I can't write soo 💀

I don't even understand ehy cuz I already told them about famidash or gbatemp etc. and SOMEHOW its ok for them

**Comment by LNLenost** [comment]
> > why dont you join the discord server for famidash? i think it would be better to ask there instead of here
> 
> My parents wont let me install discord. I can join some servers on my dad's account but I can't write messages💀
> 
> I don't even understand ehy cuz I already told them about famidash or gbatemp etc. and SOMEHOW its ok for them
